name: 'OpenTelemetry Exporter'
description: 'Collects GitHub Actions workflow metrics, traces, and logs, and exports them to Google Cloud Observability'
author: 'Jason'
branding:
  icon: 'activity'
  color: 'blue'

inputs:
  github-token:
    description: 'GitHub token for API access'
    required: true
  gcp-project-id:
    description: 'Google Cloud Project ID where metrics will be exported (defaults to project from service account key)'
    required: false
  gcp-service-account-key-file:
    description: 'Path to Google Cloud service account key JSON file (alternative to ADC/Workload Identity)'
    required: false
  service-name:
    description: 'Service name for OpenTelemetry resource attributes'
    required: false
    default: 'github-actions'
  service-namespace:
    description: 'Service namespace for OpenTelemetry resource attributes'
    required: false
    default: 'ci'
  metric-prefix:
    description: 'Prefix for metric names'
    required: false
    default: 'github.actions'

runs:
  using: 'node20'
  main: 'dist/index.js'
  post: 'dist/post/index.js'
  post-if: 'always()'
