name: 'GCP Metrics Exporter'
description: 'Collects GitHub Actions workflow metrics and traces, and exports them to Google Cloud Monitoring and Cloud Trace'
author: '@imjasonh'
branding:
  icon: 'activity'
  color: 'blue'

inputs:
  github-token:
    description: 'GitHub token for API access'
    required: true
  gcp-project-id:
    description: 'Google Cloud Project ID where metrics will be exported (defaults to project from service account key)'
    required: false
  gcp-service-account-key:
    description: 'Google Cloud service account key JSON content (use with secrets)'
    required: false
  gcp-service-account-key-file:
    description: 'Path to Google Cloud service account key JSON file (use with committed files)'
    required: false
  service-name:
    description: 'Service name for OpenTelemetry resource attributes'
    required: false
    default: 'github-actions'
  service-namespace:
    description: 'Service namespace for OpenTelemetry resource attributes'
    required: false
    default: 'ci'
  metric-prefix:
    description: 'Prefix for metric names'
    required: false
    default: 'github.actions'

outputs:
  traceparent:
    description: 'W3C Trace Context (TRACEPARENT) for creating child spans in subsequent steps'
  trace-id:
    description: 'OpenTelemetry Trace ID'
  span-id:
    description: 'Root span ID for this job'

runs:
  using: 'node20'
  main: 'dist/index.js'
  post: 'dist/post/index.js'
  post-if: 'always()'
